"""
A `LLMProvider` stand-in for background automation, used by the
`run_ai_matching` and `generate_draft_documents` scheduled tasks instead of
`AnthropicProvider`.

This milestone's instructions are explicit: "Do not add the Anthropic API
key yet" / "Stop after scheduler works with FakeLLMProvider." Living here
(not reused from a test file) because it's genuinely production code this
time — background tasks that run whether or not anyone is watching a test
suite — not a test double.

`complete()` has to answer two very different callers with the same
method, since both `MatchingEngine` and the document generators only know
about the one `LLMProvider.complete()` abstraction:

- `ai.prompt_builder.build_system_prompt()` asks for a `category_scores`
  JSON analysis — returning plain prose here would make
  `parse_response()` raise `LLMResponseError`, which `MatchingEngine`
  catches by silently falling back to rule-only scoring
  (`used_llm=False`). That would technically work, but it means "using
  FakeLLMProvider" would never actually exercise the LLM-blended scoring
  path this milestone asks the scheduler to use — so this returns a
  valid, clearly-placeholder JSON analysis instead.
- Document generators just want prose to embed in a draft — returning
  obviously-fake, clearly-labeled text (never indistinguishable from a
  real model's output) so nobody mistakes scheduler-generated draft
  content for real AI writing.

Distinguishing the two isn't done by inspecting the prompt text (fragile);
`system_prompt` for matching always contains `"category_scores"` (baked
into `ai.prompt_builder.build_system_prompt()`), which is a stable enough
signal for a fake provider whose only job is "don't call a real API."
"""

from __future__ import annotations

import json

from job_automation.ai.llm_provider import LLMProvider
from job_automation.ai.matching_models import MATCH_CATEGORIES

PLACEHOLDER_DOCUMENT_TEXT = (
    "[Automatically generated by the background scheduler using a placeholder "
    "response — no real AI provider is configured. Review and rewrite before use.]"
)


class SchedulerFakeLLMProvider(LLMProvider):
    def complete(self, *, system_prompt: str, user_prompt: str, max_tokens: int = 1024) -> str:
        if "category_scores" in system_prompt:
            return json.dumps(
                {
                    "category_scores": {category: 65.0 for category in MATCH_CATEGORIES},
                    "strengths": ["Placeholder strength from the background scheduler's fake provider."],
                    "weaknesses": ["Placeholder weakness from the background scheduler's fake provider."],
                    "missing_requirements": [],
                    "recommended_actions": ["Review this match with a real AI provider before relying on it."],
                }
            )
        return PLACEHOLDER_DOCUMENT_TEXT
