"""Add Job.closing_soon_notified_at

Revision ID: 0c09fb52cf5c
Revises: 52ad230e88b2
Create Date: 2026-07-03 10:22:41.405407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c09fb52cf5c'
down_revision: Union[str, Sequence[str], None] = '52ad230e88b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('closing_soon_notified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'closing_soon_notified_at')
    # ### end Alembic commands ###
