"""Add employer CRM tables

Revision ID: 161f6cd3b296
Revises: e9c269d9e55f
Create Date: 2026-07-03 01:09:15.325635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161f6cd3b296'
down_revision: Union[str, Sequence[str], None] = 'e9c269d9e55f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer_departments',
    sa.Column('employer_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employer_departments_employer_id'), 'employer_departments', ['employer_id'], unique=False)
    op.create_table('employer_profiles',
    sa.Column('employer_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_favourite', sa.Boolean(), nullable=False),
    sa.Column('visa_sponsorship_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employer_id', 'user_id', name='uq_employer_profiles_employer_id_user_id')
    )
    op.create_index(op.f('ix_employer_profiles_employer_id'), 'employer_profiles', ['employer_id'], unique=False)
    op.create_index(op.f('ix_employer_profiles_is_favourite'), 'employer_profiles', ['is_favourite'], unique=False)
    op.create_index(op.f('ix_employer_profiles_user_id'), 'employer_profiles', ['user_id'], unique=False)
    op.create_table('employer_contacts',
    sa.Column('employer_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['employer_departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employer_contacts_department_id'), 'employer_contacts', ['department_id'], unique=False)
    op.create_index(op.f('ix_employer_contacts_employer_id'), 'employer_contacts', ['employer_id'], unique=False)
    op.create_index(op.f('ix_employer_contacts_user_id'), 'employer_contacts', ['user_id'], unique=False)
    op.create_table('employer_activity_log',
    sa.Column('employer_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['employer_contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employer_activity_log_contact_id'), 'employer_activity_log', ['contact_id'], unique=False)
    op.create_index(op.f('ix_employer_activity_log_employer_id'), 'employer_activity_log', ['employer_id'], unique=False)
    op.create_index(op.f('ix_employer_activity_log_entry_type'), 'employer_activity_log', ['entry_type'], unique=False)
    op.create_index(op.f('ix_employer_activity_log_occurred_at'), 'employer_activity_log', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_employer_activity_log_user_id'), 'employer_activity_log', ['user_id'], unique=False)
    op.add_column('employers', sa.Column('employer_type', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_employers_employer_type'), 'employers', ['employer_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employers_employer_type'), table_name='employers')
    op.drop_column('employers', 'employer_type')
    op.drop_index(op.f('ix_employer_activity_log_user_id'), table_name='employer_activity_log')
    op.drop_index(op.f('ix_employer_activity_log_occurred_at'), table_name='employer_activity_log')
    op.drop_index(op.f('ix_employer_activity_log_entry_type'), table_name='employer_activity_log')
    op.drop_index(op.f('ix_employer_activity_log_employer_id'), table_name='employer_activity_log')
    op.drop_index(op.f('ix_employer_activity_log_contact_id'), table_name='employer_activity_log')
    op.drop_table('employer_activity_log')
    op.drop_index(op.f('ix_employer_contacts_user_id'), table_name='employer_contacts')
    op.drop_index(op.f('ix_employer_contacts_employer_id'), table_name='employer_contacts')
    op.drop_index(op.f('ix_employer_contacts_department_id'), table_name='employer_contacts')
    op.drop_table('employer_contacts')
    op.drop_index(op.f('ix_employer_profiles_user_id'), table_name='employer_profiles')
    op.drop_index(op.f('ix_employer_profiles_is_favourite'), table_name='employer_profiles')
    op.drop_index(op.f('ix_employer_profiles_employer_id'), table_name='employer_profiles')
    op.drop_table('employer_profiles')
    op.drop_index(op.f('ix_employer_departments_employer_id'), table_name='employer_departments')
    op.drop_table('employer_departments')
    # ### end Alembic commands ###
