"""add notification preferences and email outbox tables

Revision ID: 3486759c557c
Revises: c38bf18c2826
Create Date: 2026-07-03 14:31:02.376307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3486759c557c'
down_revision: Union[str, Sequence[str], None] = 'c38bf18c2826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email_new_jobs_imported', sa.Boolean(), nullable=False),
    sa.Column('email_high_match', sa.Boolean(), nullable=False),
    sa.Column('email_interview_reminders', sa.Boolean(), nullable=False),
    sa.Column('email_closing_soon', sa.Boolean(), nullable=False),
    sa.Column('email_daily_digest', sa.Boolean(), nullable=False),
    sa.Column('email_weekly_summary', sa.Boolean(), nullable=False),
    sa.Column('email_scheduler_status', sa.Boolean(), nullable=False),
    sa.Column('email_document_generated', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.Integer(), nullable=True),
    sa.Column('quiet_hours_end', sa.Integer(), nullable=True),
    sa.Column('daily_digest_hour', sa.Integer(), nullable=False),
    sa.Column('last_daily_digest_sent_date', sa.Date(), nullable=True),
    sa.Column('last_weekly_summary_sent_week', sa.String(length=10), nullable=True),
    sa.Column('ai_match_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('preferred_email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('email_outbox',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('notification_id', sa.Uuid(), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_outbox_notification_id'), 'email_outbox', ['notification_id'], unique=False)
    op.create_index(op.f('ix_email_outbox_notification_type'), 'email_outbox', ['notification_type'], unique=False)
    op.create_index(op.f('ix_email_outbox_status'), 'email_outbox', ['status'], unique=False)
    op.create_index(op.f('ix_email_outbox_to_email'), 'email_outbox', ['to_email'], unique=False)
    op.create_index(op.f('ix_email_outbox_user_id'), 'email_outbox', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_outbox_user_id'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_to_email'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_status'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_notification_type'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_notification_id'), table_name='email_outbox')
    op.drop_table('email_outbox')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
