"""Add interview management tables

Revision ID: 52ad230e88b2
Revises: 161f6cd3b296
Create Date: 2026-07-03 02:34:22.811421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ad230e88b2'
down_revision: Union[str, Sequence[str], None] = '161f6cd3b296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_records',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('employer_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('application_workflow_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('interview_type', sa.String(length=30), nullable=False),
    sa.Column('interview_stage', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('meeting_link', sa.String(length=1000), nullable=True),
    sa.Column('interviewer_names', sa.JSON(), nullable=True),
    sa.Column('reminder_offsets', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_workflow_id'], ['application_workflows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['employer_contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_records_application_workflow_id'), 'interview_records', ['application_workflow_id'], unique=False)
    op.create_index(op.f('ix_interview_records_contact_id'), 'interview_records', ['contact_id'], unique=False)
    op.create_index(op.f('ix_interview_records_employer_id'), 'interview_records', ['employer_id'], unique=False)
    op.create_index(op.f('ix_interview_records_interview_type'), 'interview_records', ['interview_type'], unique=False)
    op.create_index(op.f('ix_interview_records_job_id'), 'interview_records', ['job_id'], unique=False)
    op.create_index(op.f('ix_interview_records_scheduled_at'), 'interview_records', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_interview_records_status'), 'interview_records', ['status'], unique=False)
    op.create_index(op.f('ix_interview_records_user_id'), 'interview_records', ['user_id'], unique=False)
    op.create_table('interview_checklist_items',
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_checklist_items_interview_id'), 'interview_checklist_items', ['interview_id'], unique=False)
    op.create_index(op.f('ix_interview_checklist_items_is_complete'), 'interview_checklist_items', ['is_complete'], unique=False)
    op.create_table('interview_notes',
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_notes_category'), 'interview_notes', ['category'], unique=False)
    op.create_index(op.f('ix_interview_notes_interview_id'), 'interview_notes', ['interview_id'], unique=False)
    op.create_table('interview_reminders',
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('offset', sa.String(length=20), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_reminders_interview_id'), 'interview_reminders', ['interview_id'], unique=False)
    op.create_index(op.f('ix_interview_reminders_is_sent'), 'interview_reminders', ['is_sent'], unique=False)
    op.create_index(op.f('ix_interview_reminders_offset'), 'interview_reminders', ['offset'], unique=False)
    op.create_index(op.f('ix_interview_reminders_remind_at'), 'interview_reminders', ['remind_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_reminders_remind_at'), table_name='interview_reminders')
    op.drop_index(op.f('ix_interview_reminders_offset'), table_name='interview_reminders')
    op.drop_index(op.f('ix_interview_reminders_is_sent'), table_name='interview_reminders')
    op.drop_index(op.f('ix_interview_reminders_interview_id'), table_name='interview_reminders')
    op.drop_table('interview_reminders')
    op.drop_index(op.f('ix_interview_notes_interview_id'), table_name='interview_notes')
    op.drop_index(op.f('ix_interview_notes_category'), table_name='interview_notes')
    op.drop_table('interview_notes')
    op.drop_index(op.f('ix_interview_checklist_items_is_complete'), table_name='interview_checklist_items')
    op.drop_index(op.f('ix_interview_checklist_items_interview_id'), table_name='interview_checklist_items')
    op.drop_table('interview_checklist_items')
    op.drop_index(op.f('ix_interview_records_user_id'), table_name='interview_records')
    op.drop_index(op.f('ix_interview_records_status'), table_name='interview_records')
    op.drop_index(op.f('ix_interview_records_scheduled_at'), table_name='interview_records')
    op.drop_index(op.f('ix_interview_records_job_id'), table_name='interview_records')
    op.drop_index(op.f('ix_interview_records_interview_type'), table_name='interview_records')
    op.drop_index(op.f('ix_interview_records_employer_id'), table_name='interview_records')
    op.drop_index(op.f('ix_interview_records_contact_id'), table_name='interview_records')
    op.drop_index(op.f('ix_interview_records_application_workflow_id'), table_name='interview_records')
    op.drop_table('interview_records')
    # ### end Alembic commands ###
