"""Add application workflow tables

Revision ID: 63654f3e5360
Revises: 43d2f89f498d
Create Date: 2026-07-01 14:41:59.719798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63654f3e5360'
down_revision: Union[str, Sequence[str], None] = '43d2f89f498d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_workflows',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('job_match_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['job_match_id'], ['job_matches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_application_workflows_user_id_job_id')
    )
    op.create_index(op.f('ix_application_workflows_job_id'), 'application_workflows', ['job_id'], unique=False)
    op.create_index(op.f('ix_application_workflows_job_match_id'), 'application_workflows', ['job_match_id'], unique=False)
    op.create_index(op.f('ix_application_workflows_status'), 'application_workflows', ['status'], unique=False)
    op.create_index(op.f('ix_application_workflows_user_id'), 'application_workflows', ['user_id'], unique=False)
    op.create_table('workflow_audit_logs',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['application_workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_audit_logs_action'), 'workflow_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_workflow_audit_logs_workflow_id'), 'workflow_audit_logs', ['workflow_id'], unique=False)
    op.create_table('workflow_status_history',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['application_workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_status_history_workflow_id'), 'workflow_status_history', ['workflow_id'], unique=False)
    # SQLite can't ALTER a table to add a foreign key constraint directly —
    # batch mode recreates the table under the hood (copy-and-move strategy)
    # to work around that limitation.
    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_generated_documents_workflow_id'), ['workflow_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_generated_documents_workflow_id_application_workflows',
            'application_workflows', ['workflow_id'], ['id'], ondelete='SET NULL'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_generated_documents_workflow_id_application_workflows', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_generated_documents_workflow_id'))
        batch_op.drop_column('workflow_id')
    op.drop_index(op.f('ix_workflow_status_history_workflow_id'), table_name='workflow_status_history')
    op.drop_table('workflow_status_history')
    op.drop_index(op.f('ix_workflow_audit_logs_workflow_id'), table_name='workflow_audit_logs')
    op.drop_index(op.f('ix_workflow_audit_logs_action'), table_name='workflow_audit_logs')
    op.drop_table('workflow_audit_logs')
    op.drop_index(op.f('ix_application_workflows_user_id'), table_name='application_workflows')
    op.drop_index(op.f('ix_application_workflows_status'), table_name='application_workflows')
    op.drop_index(op.f('ix_application_workflows_job_match_id'), table_name='application_workflows')
    op.drop_index(op.f('ix_application_workflows_job_id'), table_name='application_workflows')
    op.drop_table('application_workflows')
    # ### end Alembic commands ###
