"""Add NHS job detail fields to Job model

Revision ID: 75a188d09ece
Revises: d93073b3212b
Create Date: 2026-07-01 09:41:46.081700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a188d09ece'
down_revision: Union[str, Sequence[str], None] = 'd93073b3212b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('salary_raw', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('band', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('contract_type', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('working_pattern', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('closing_date', sa.Date(), nullable=True))
    op.add_column('jobs', sa.Column('requirements', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('benefits', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_jobs_closing_date'), 'jobs', ['closing_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_closing_date'), table_name='jobs')
    op.drop_column('jobs', 'benefits')
    op.drop_column('jobs', 'requirements')
    op.drop_column('jobs', 'closing_date')
    op.drop_column('jobs', 'working_pattern')
    op.drop_column('jobs', 'contract_type')
    op.drop_column('jobs', 'band')
    op.drop_column('jobs', 'salary_raw')
    # ### end Alembic commands ###
