"""Add visa sponsorship to Job and analysis to JobMatch

Revision ID: e167f5bf7f2e
Revises: 75a188d09ece
Create Date: 2026-07-01 11:11:12.312559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e167f5bf7f2e'
down_revision: Union[str, Sequence[str], None] = '75a188d09ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('analysis', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('visa_sponsorship', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'visa_sponsorship')
    op.drop_column('job_matches', 'analysis')
    # ### end Alembic commands ###
