"""Add saved_jobs and job_reminders tables

Revision ID: e9c269d9e55f
Revises: bfbc84b1875c
Create Date: 2026-07-02 14:09:18.004127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c269d9e55f'
down_revision: Union[str, Sequence[str], None] = 'bfbc84b1875c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_jobs',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('is_favourite', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('personal_rating', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('interview_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'user_id', name='uq_saved_jobs_job_id_user_id')
    )
    op.create_index(op.f('ix_saved_jobs_is_archived'), 'saved_jobs', ['is_archived'], unique=False)
    op.create_index(op.f('ix_saved_jobs_is_favourite'), 'saved_jobs', ['is_favourite'], unique=False)
    op.create_index(op.f('ix_saved_jobs_is_hidden'), 'saved_jobs', ['is_hidden'], unique=False)
    op.create_index(op.f('ix_saved_jobs_is_saved'), 'saved_jobs', ['is_saved'], unique=False)
    op.create_index(op.f('ix_saved_jobs_job_id'), 'saved_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_saved_jobs_pipeline_stage'), 'saved_jobs', ['pipeline_stage'], unique=False)
    op.create_index(op.f('ix_saved_jobs_user_id'), 'saved_jobs', ['user_id'], unique=False)
    op.create_table('job_reminders',
    sa.Column('saved_job_id', sa.Uuid(), nullable=False),
    sa.Column('reminder_type', sa.String(length=30), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['saved_job_id'], ['saved_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_reminders_is_sent'), 'job_reminders', ['is_sent'], unique=False)
    op.create_index(op.f('ix_job_reminders_remind_at'), 'job_reminders', ['remind_at'], unique=False)
    op.create_index(op.f('ix_job_reminders_reminder_type'), 'job_reminders', ['reminder_type'], unique=False)
    op.create_index(op.f('ix_job_reminders_saved_job_id'), 'job_reminders', ['saved_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_reminders_saved_job_id'), table_name='job_reminders')
    op.drop_index(op.f('ix_job_reminders_reminder_type'), table_name='job_reminders')
    op.drop_index(op.f('ix_job_reminders_remind_at'), table_name='job_reminders')
    op.drop_index(op.f('ix_job_reminders_is_sent'), table_name='job_reminders')
    op.drop_table('job_reminders')
    op.drop_index(op.f('ix_saved_jobs_user_id'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_pipeline_stage'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_job_id'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_is_saved'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_is_hidden'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_is_favourite'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_is_archived'), table_name='saved_jobs')
    op.drop_table('saved_jobs')
    # ### end Alembic commands ###
